name: "My Goo Site"
output: "build"
static: "static"
global: 
  everywhere: "data/global.yaml"
partials:
  header: "partials/header.tmpl"
  footer: "partials/footer.tmpl"
# shortcodes:
#   - row: "shortcodes/post.tmpl"
#   - img: "shortcodes/img.tmpl"
pages:
  - title: "Home"
    path: "/"
    template: "templates/home.tmpl"
    data:
      home: "data/home.yaml"

  - title: "Store"
    path: "/store/"
    template: "templates/store.tmpl"
# collections: