# Specify site name, output folder, static folder.
name: My Goo Site
output: build
static_src: static
static_dest: "."

# Global variable files.
global:
    everywhere: data/global.yaml

# Partials.
partials:
    header: views/partials/header.tmpl
    footer: views/partials/footer.tmpl

# Pages.
pages:
    - title: Home
      path: /
      template: views/home.tmpl
      data:
          home: data/home.yaml

    - title: Store
      path: /store/
      template: views/store.tmpl

# Collections.
collections:
    - title: Blog Posts
      path: /blog
      template: views/blog.tmpl
      posts: posts
